-- ====================================================================
-- SMART TOKEN MANAGEMENT SYSTEM - SUPABASE INITIALIZATION SCRIPT
-- Copy and paste ALL of this into your Supabase SQL Editor and click RUN
-- ====================================================================

-- 1. Create Tokens Table
CREATE TABLE IF NOT EXISTS tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_number INT NOT NULL UNIQUE,
    customer_name TEXT,
    phone_number TEXT,
    email TEXT,
    service_type TEXT,
    source TEXT,
    status TEXT DEFAULT 'Waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    remarks TEXT,
    completed_at TIMESTAMPTZ
);

-- 2. Create Settings Table
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insert Default System Settings
INSERT INTO settings (key, value) VALUES
    ('Starting Token Number', '1'),
    ('Last Generated Token', '0'),
    ('Current Serving Token', '0'),
    ('Average Service Time', '10'),
    ('Organization Name', 'Smart Token Management System'),
    ('Admin Username', 'admin'),
    ('Admin Email', 'admin@example.com'),
    ('Admin Password', 'admin123'),
    ('Admin OTP', ''),
    ('Admin OTP Expiry', ''),
    ('Enable Buzzer', 'true'),
    ('Thermal Printer Settings', '{"connection":"bluetooth","device":""}'),
    ('Scanned Bluetooth Printers', '[]'),
    ('Scan Request', 'false'),
    ('Test Print Request', ''),
    ('ESP32 Master Status', '{"online":true,"wifi_ssid":"GSV_Electrical_Enterprises","ip_address":"192.168.1.100"}')
ON CONFLICT (key) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 5. Drop existing policies if any
DROP POLICY IF EXISTS "Allow anon read access on tokens" ON tokens;
DROP POLICY IF EXISTS "Allow anon insert access on tokens" ON tokens;
DROP POLICY IF EXISTS "Allow anon update access on tokens" ON tokens;
DROP POLICY IF EXISTS "Allow anon delete access on tokens" ON tokens;

DROP POLICY IF EXISTS "Allow anon read access on settings" ON settings;
DROP POLICY IF EXISTS "Allow anon update access on settings" ON settings;
DROP POLICY IF EXISTS "Allow anon insert access on settings" ON settings;

-- 6. Create Open Permissive Policies for Web & ESP32
CREATE POLICY "Allow anon read access on tokens" ON tokens FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert access on tokens" ON tokens FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update access on tokens" ON tokens FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon delete access on tokens" ON tokens FOR DELETE TO anon USING (true);

CREATE POLICY "Allow anon read access on settings" ON settings FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert access on settings" ON settings FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update access on settings" ON settings FOR UPDATE TO anon USING (true) WITH CHECK (true);
