-- Create Tokens Table
CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_number INT NOT NULL UNIQUE,
    customer_name TEXT,
    phone_number TEXT,
    email TEXT,
    service_type TEXT,
    source TEXT,
    status TEXT DEFAULT 'Waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    remarks TEXT,
    completed_at TIMESTAMPTZ
);

-- Create Settings Table
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Default Settings - ALL REQUIRED KEYS MUST BE INITIALIZED
INSERT INTO settings (key, value) VALUES
    -- Core Token Settings
    ('Starting Token Number', '1'),
    ('Last Generated Token', '0'),
    ('Current Serving Token', '0'),
    ('Average Service Time', '10'),
    ('Organization Name', 'Smart Token Management System'),
    
    -- Admin Credentials (CRITICAL - Must be set before using)
    ('Admin Username', 'admin'),
    ('Admin Email', 'admin@example.com'),
    ('Admin Password', 'admin123'),
    ('Admin OTP', ''),
    ('Admin OTP Expiry', ''),
    
    -- System Features
    ('Enable Buzzer', 'true'),
    ('Thermal Printer Settings', '{"connection":"wire","device":""}'),
    ('Scanned Bluetooth Printers', '[]'),
    
    -- Email Configuration
    ('Email Service Config', '{"provider":"demo","resend_api_key":"","resend_sender":"onboarding@resend.dev","smtp_host":"","smtp_port":587,"smtp_username":"","smtp_password":"","smtp_sender":"noreply@yourdomain.com","smtp_ssl":false}'),
    
    -- Bluetooth Scan Status
    ('Scan Request', 'false');

-- Enable RLS on tables
ALTER TABLE tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create policies for tokens table
CREATE POLICY "Allow anon read access on tokens" ON tokens FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert access on tokens" ON tokens FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update access on tokens" ON tokens FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon delete access on tokens" ON tokens FOR DELETE TO anon USING (true);

-- Create policies for settings table
CREATE POLICY "Allow anon read access on settings" ON settings FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon update access on settings" ON settings FOR UPDATE TO anon USING (true) WITH CHECK (true);
